apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-agent
  namespace: devops-agent

spec:
  replicas: 1

  selector:
    matchLabels:
      app: devops-agent

  template:
    metadata:
      labels:
        app: devops-agent

    spec:
      containers:
      - name: devops-agent

        image: 145043400170.dkr.ecr.eu-north-1.amazonaws.com/pavan-devops-ecr:v1.0.0

        imagePullPolicy: Always

        ports:
        - containerPort: 8000

        envFrom:
        - secretRef:
            name: devops-agent-secret

        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"