apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: devops-agent
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/iam-pavanpachuru/github-ai-agent-web.git
    targetRevision: main
    path: app

  destination:
    server: https://kubernetes.default.svc
    namespace: devops-agent

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true